export const LOAD_TIMELINE_SUCCESS = 'LOAD_TIMELINE_SUCCESS';
export const CREATE_TIMELINE_ROW_SUCCESS = 'CREATE_TIMELINE_ROW_SUCCESS';
export const UPDATE_TIMELINE_ROW_SUCCESS = 'UPDATE_TIMELINE_ROW_SUCCESS';
